# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-27 10:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u5173\u952e\u8bcd\u914d\u7f6e',
                'verbose_name_plural': '\u5173\u952e\u8bcd\u914d\u7f6e\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='\u6807\u9898')),
                ('url', models.URLField(verbose_name='\u94fe\u63a5')),
                ('content', models.TextField(null=True, verbose_name='\u5907\u6ce8')),
                ('publish_at', models.DateTimeField(verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='\u722c\u53d6\u65f6\u95f4')),
                ('keys', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backstage.Keys', verbose_name='\u5173\u952e\u8bcd')),
            ],
            options={
                'verbose_name': '\u65b0\u95fb',
                'verbose_name_plural': '\u65b0\u95fb\u7ba1\u7406',
            },
        ),
    ]
